In [7]:
import tensorflow as tf

In [8]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.


In [9]:
print(tf.__version__)

2.15.0


In [11]:
  #Create two tensors with constant variable
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.EagerTensor

In [13]:
# Perform a mathematical operation which also results in a tensor
tensor_1 + tensor_2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
#Want to check the type of the result?
result = tensor_1 + tensor_2
print(result)

tf.Tensor(3, shape=(), dtype=int32)


In [52]:
# How to check its value?
print(result.numpy())

3


In [55]:
with tf.Session() as sess:
    result = sess.run(tensor_1+tensor_2)
print(result)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [56]:
sess = tf.compat.v1.Session()
print(sess)

In [22]:
sess.close()

In [23]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [24]:
n3 = n1 + n2

In [35]:
print(n3)
print(n3.numpy())

tf.Tensor(3, shape=(), dtype=int32)
3


In [36]:
@tf.function
def add_nodes(tensor1, tensor2):
    return tensor1 + tensor2

g_n3 = add_nodes(n1,n2)
print(g_n3)
print(g_n3.numpy())

tf.Tensor(3, shape=(), dtype=int32)
3


In [37]:
 g = tf.Graph()

In [38]:
print(g)

In [44]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])
print (A.numpy())

[[3 2]
 [5 2]]


In [46]:
# Making a Variable tensor VA, which can change. Notice it's Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])
       
print(VA.numpy())


[[3 2]
 [5 2]]


In [72]:
# Making another tensor B
B = tf.constant([[9, 5],
                [1, 3]])
print(B.numpy())

[[9 5]
 [1 3]]


In [73]:
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{}').format(
      AB_concatenated.numpy()
))


Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [74]:
# Try concatenating to columns
## ENTER YOUR CODE HERE!!!
# Making a tensor with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
      tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [75]:
# Making a tensor filled with zero with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{}').format(
     tensor.numpy()
))


Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [99]:
 # Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                     [5, 2],
                     [9, 5],
                     [1, 3]])

In [100]:
# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                            shape = [1, 8])
print(('Tensor BEFORE reshape:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor AFTER reshape:\n{0}').format(
      reshaped_tensor.numpy()
     ))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


In [101]:
# Making a Tensor
tensor = tf.constant([[3.1, 2.8],
                     [5.2, 2.3],
                     [9.7, 5.5],
                     [1.1, 3.4]],
                     dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

print(('Tensor with floats:\n{0}').format(
       tensor.numpy()
))
print(('\nTensor cast from float to int (just remove the \   decimal, no rounding):\n{0}').format(tensor_as_int.numpy()))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the \   decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [102]:
# Some Matrix A
A = tf.constant([[3, 7],
               [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(A))

The transposed matrix A:
[[3 1]
 [7 9]]


In [107]:
# Some Matrix A
A = tf.constant([[3, 7],
               [1, 9]])

# Some vector v
v = tf.constant([[5],
                 [2]])
# Matrix multiplication of A.V T

Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new \  Tensor:\n{0}').format(Av))

Matrix Multiplication of A and v results in a new \  Tensor:
[[29]
 [23]]


In [108]:
# Element -wise multiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a \ new Tensor:\n{0}').format(Av))

Element-wise multiplication of A and v results in a \ new Tensor:
[[15 35]
 [ 2 18]]


In [121]:
# Some Matrix A 
A = tf.constant([[3, 7],
                [1, 9],
                [2, 5]])
# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(rows, columns))
# Making identify matrix
A_identity = tf.eye(num_rows = rows,
                   num_columns = columns,
                   dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(A_identity.numpy()))


Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


In [122]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                [1, 9]])
# Determine must be: half, float32, float64, completed64,completed128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)
print(('The determinan of A:\n{0}').format(det_A))

The determinan of A:
20.0


In [123]:
# Defining a 3x3 matrix A
A = tf.constant ([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])
# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                [91, 10, 95],
                [37, 13, 45]])
# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in new Tensor:\n{0}').format(dot_AB))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
AB =tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format)

Dot product of A.B^T results in new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]
<built-in method format of str object at 0x000001E8E7A68A40>
